# Generated by Django 4.2.16 on 2024-09-23 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('work_time', models.DurationField(default=0)),
                ('break_time', models.DurationField(default=0)),
            ],
        ),
    ]
