# Generated by Django 4.2.16 on 2024-09-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
